/**
 * BNS Lang v2.0 — IEC 61131-3 Structured Text generator
 */

const { collectSymbols } = require('../ir');

function varName(sym) {
  return `${sym.type}${sym.index}`;
}

function exprToST(node) {
  if (!node) return 'TRUE';
  if (node.type && node.index !== undefined) {
    const v = varName(node);
    return node.negated ? `NOT ${v}` : v;
  }
  if (node.op === 'AND') {
    const s = node.children.map(c => exprToST(c)).join(' AND ');
    return node.children.length > 1 ? `(${s})` : s;
  }
  if (node.op === 'OR') {
    return '(' + node.children.map(c => exprToST(c)).join(' OR ') + ')';
  }
  return 'TRUE';
}

function xgtAddress(sym) {
  const { type, index } = sym;
  if (type === 'X') return `%IX0.${index}`;
  if (type === 'Y') return `%QX1.${index % 100}`;
  if (type === 'M') return `%MX${index}`;
  if (type === 'T') return `%TX${index}`;
  if (type === 'C') return `%CX${index}`;
  return `%MX${index}`;
}

function generate(ast, options = {}) {
  const header = options.header !== false ? '(* Generated by BNS Lang v2.0 *)' : '';
  const symbols = collectSymbols(ast);
  const varLines = symbols.map(s => {
    const at = options.noAddress ? '' : ` AT ${xgtAddress(s)}`;
    return `  ${varName(s)}${at} : BOOL;`;
  });

  const stLines = [];
  ast.rungs.forEach((rung, i) => {
    if (rung.comments.length) {
      rung.comments.forEach(c => stLines.push(`  (* ${c} *)`));
    }
    rung.coils.forEach(coil => {
      const outVar = varName(coil.symbol);
      const cond = exprToST(rung.conditions);
      if (coil.kind === 'SET') {
        stLines.push(`  ${outVar} := TRUE;`);
      } else if (coil.kind === 'RESET') {
        stLines.push(`  ${outVar} := FALSE;`);
      } else if (coil.preset && (coil.symbol.type === 'T' || coil.symbol.type === 'C')) {
        stLines.push(`  (* ${outVar} preset ${coil.preset}${coil.presetType === 'ms' ? 'ms' : ''} *)`);
        stLines.push(`  ${outVar} := ${cond};`);
      } else {
        stLines.push(`  ${outVar} := ${cond};`);
      }
    });
  });

  const varBlock = varLines.length
    ? `VAR\n${varLines.join('\n')}\nEND_VAR\n\n`
    : '';

  return `${header}\n\nPROGRAM MAIN\n${varBlock}${stLines.join('\n')}\n\nEND_PROGRAM\n`;
}

module.exports = { generate, exprToST, varName };
